// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62zFy9jatehQ9Ce2JOKhUNJoPGgSHPNY',
    appId: '1:1012207625893:web:2135e94507244b88188f4c',
    messagingSenderId: '1012207625893',
    projectId: 'wreniq-906a6',
    authDomain: 'wreniq-906a6.firebaseapp.com',
    storageBucket: 'wreniq-906a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIctfL5Az13IanjxtMdaijOO36EsPXKY4',
    appId: '1:1012207625893:android:a3abc600ccd1ea36188f4c',
    messagingSenderId: '1012207625893',
    projectId: 'wreniq-906a6',
    storageBucket: 'wreniq-906a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlAPWNr7TGp1RKIZtMzikXqb06eOZkjI',
    appId: '1:1012207625893:ios:7f84ff2e80708cbb188f4c',
    messagingSenderId: '1012207625893',
    projectId: 'wreniq-906a6',
    storageBucket: 'wreniq-906a6.firebasestorage.app',
    iosBundleId: 'com.example.wreniq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlAPWNr7TGp1RKIZtMzikXqb06eOZkjI',
    appId: '1:1012207625893:ios:7f84ff2e80708cbb188f4c',
    messagingSenderId: '1012207625893',
    projectId: 'wreniq-906a6',
    storageBucket: 'wreniq-906a6.firebasestorage.app',
    iosBundleId: 'com.example.wreniq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62zFy9jatehQ9Ce2JOKhUNJoPGgSHPNY',
    appId: '1:1012207625893:web:8b914d69bf1d0760188f4c',
    messagingSenderId: '1012207625893',
    projectId: 'wreniq-906a6',
    authDomain: 'wreniq-906a6.firebaseapp.com',
    storageBucket: 'wreniq-906a6.firebasestorage.app',
  );
}
